services:
  detector_service:
    image: basketball-detector
    build:
      context: .
      dockerfile: services/detector_service/Dockerfile
    container_name: detector_service
    ports:
      - "8001:8000"
    networks:
      - shared
    environment:
      MINIO_ENDPOINT: "http://minio:9000"
      ROBOFLOW_API_KEY: ${ROBOFLOW_API_KEY}
      WNB_API_TOKEN: ${WNB_API_TOKEN}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  court-service:
    build:
      context: .
      dockerfile: services/court_service/Dockerfile
    image: court-service
    container_name: court-service
    ports:
      - "8003:8000"
    networks:
      - shared
    environment:
      MINIO_ENDPOINT: "http://minio:9000"
      ROBOFLOW_API_KEY: ${ROBOFLOW_API_KEY}
      WNB_API_TOKEN: ${WNB_API_TOKEN}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    depends_on:
      - minio
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ui-service:
    build:
      context: .
      dockerfile: services/ui_service/Dockerfile
    image: ui-service
    container_name: ui-service
    ports:
      - "7860:7860"
    networks:
      - shared      
    environment:
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

      API_URL_PROCESS: "http://orchestrator_service:8000/process"
      API_URL_STITCH: "http://court-service:8000/stitch"
      API_URL_WARP: "http://court-service:8000/warp_panorama"
      API_URL_VIEWER: "http://video_viewer_service:8000"
    depends_on:
      - minio
      - orchestrator_service
      - court-service
      - video_viewer_service

  team_assigner_service:
    image: basketball-team-assigner
    build:
      context: .
      dockerfile: services/team_assigner_service/Dockerfile
    container_name: team_assigner_service
    ports:
      - "8002:8000"
    networks:
      - shared      
    environment:
      MINIO_ENDPOINT: "http://minio:9000"
      ROBOFLOW_API_KEY: ${ROBOFLOW_API_KEY}
      WNB_API_TOKEN: ${WNB_API_TOKEN}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  video_viewer_service:
    build:
      context: .
      dockerfile: services/video_viewer_service/Dockerfile
    image: basketball-video-viewer
    container_name: video_viewer_service
    ports:
      - "8004:8000"
    networks:
      - shared      
    environment:
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    depends_on:
      - minio

  orchestrator_service:
    image: basketball-orchestrator
    build:
      context: .
      dockerfile: services/orchestrator_service/Dockerfile
    container_name: orchestrator_service
    ports:
      - "8000:8000"
    networks:
      - shared      
    depends_on:
      - detector_service
      - team_assigner_service
    environment:
      DETECTOR_URL: "http://detector_service:8000/track"
      TEAM_ASSIGNER_URL: "http://team_assigner_service:8000/assign_teams"
      HOMOGRAPHY_URL: "http://court-service:8000/homographyvideo"
      MINIO_ENDPOINT: "http://minio:9000"
      ROBOFLOW_API_KEY: ${ROBOFLOW_API_KEY}
      WNB_API_TOKEN: ${WNB_API_TOKEN}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

  minio:
    image: minio/minio
    container_name: minio
    networks:
      - shared      
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    networks:
        - shared      
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    ports:
      - "8081:8081"
    networks:
      - shared      
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/
      ME_CONFIG_MONGODB_TIMEOUT: "30000"
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - shared
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

volumes:
  minio-data:
  mongo-data:

networks:
  shared:
    external: true