services:
  detector_service:
    image: basketball-detector
    build:
      context: .
      dockerfile: services/detector_service/Dockerfile
    container_name: detector_service
    ports:
      - "8000:8000"
    environment:
      ROBOFLOW_API_KEY: ${ROBOFLOW_API_KEY}
      NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
      WNB_API_TOKEN: ${WNB_API_TOKEN}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  team_assigner_service:
    image: basketball-team-assigner
    build:
      context: .
      dockerfile: services/team_assigner_service/Dockerfile
    container_name: team_assigner_service
    ports:
      - "8001:8001"
    environment:
      ROBOFLOW_API_KEY: ${ROBOFLOW_API_KEY}
      NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
      WNB_API_TOKEN: ${WNB_API_TOKEN}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  orchestrator_service:
    image: basketball-orchestrator
    build:
      context: .
      dockerfile: services/orchestrator_service/Dockerfile
    container_name: orchestrator_service
    ports:
      - "8002:8002"
    depends_on:
      - detector_service
      - team_assigner_service
    environment:
      DETECTOR_URL: "http://detector_service:8000/track"
      TEAM_ASSIGNER_URL: "http://team_assigner_service:8001/assign_teams"
      ROBOFLOW_API_KEY: ${ROBOFLOW_API_KEY}
      NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
      WNB_API_TOKEN: ${WNB_API_TOKEN}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}