global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'detector'
    static_configs:
      - targets: ['detector_service:8000']

  - job_name: 'court_service'
    static_configs:
      - targets: ['court-service:8000']

  - job_name: 'team_assigner'
    static_configs:
      - targets: ['team_assigner_service:8000']

  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator_service:8000']

  - job_name: 'viewer'
    static_configs:
      - targets: ['video_viewer_service:8000']
