_wandb:
    value:
        cli_version: 0.23.0
        e:
            hc2zds38vqgxbupgnroaqbydmdcwebu0:
                codePath: /home/maso/university/advanced_ai_systems_vt2025p2/Basketball-Tracker/wnb_artifacts.ipynb
                codePathLocal: wnb_artifacts.ipynb
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1081101176832"
                        used: "37033435136"
                email: mahmut.osmanovic@outlook.com
                executable: /home/maso/miniconda3/envs/abs/bin/python
                git:
                    commit: 7783d623acb2070387cf306385b11bb2db21e6d8
                    remote: git@github.com:mosmar99/Basketball-Tracker.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-591bfa15-4035-1069-2b67-e8d6224daa81
                host: maso
                memory:
                    total: "58965704704"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/maso/university/advanced_ai_systems_vt2025p2/Basketball-Tracker/wnb_artifacts.ipynb
                python: CPython 3.12.12
                root: /home/maso/university/advanced_ai_systems_vt2025p2/Basketball-Tracker
                startedAt: "2025-11-20T13:51:52.775568Z"
                writerId: hc2zds38vqgxbupgnroaqbydmdcwebu0
        m: []
        python_version: 3.12.12
        t:
            "3":
                - 2
            "4": 3.12.12
            "5": 0.23.0
            "8":
                - 1
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
